title: 'Codes & Notes'
languageCode: 'en-us'
buildDrafts: false
pluralizelisttitles: false
relativeUrls: true

SectionPagesMenu: 'main'
metaDataFormat: 'yaml'
# baseURL: 'http://codesandnotes.com/'
baseurl: ''
# theme: 'codesandnotes'

layoutdir: 'app/layouts'
publishdir: 'dist'

taxonomies:
  tag: 'tags'

params:
  foo: 'bar'
