title: 'Codes & Notes'
languageCode: 'en-us'
buildDrafts: false
pluralizelisttitles: false
relativeUrls: true

SectionPagesMenu: 'main'
metaDataFormat: 'yaml'
# baseURL: 'http://codesandnotes.com/'
# baseurl: ''
# theme: 'codesandnotes'
relativeURLs: true

layoutdir: 'app/layouts'
publishdir: 'dist'

taxonomies:
  tag: 'tags'

params:
  foo: 'bar'

menu:
  main:
    - name: "Tools and Workflow"
      #weight: -120
      Identifier: "Tools and Workflow"
      url: "/tools-and-workflow"
