title: 'Codes & Notes'
languageCode: 'en-us'
buildDrafts: false
pluralizelisttitles: false
Paginate: 999
SectionPagesMenu: 'main'
metaDataFormat: 'yaml'
ignoreFiles: ["\\_drafts$"]

relativeURLs: true
#baseURL: 'http://codesandnotes.com/'
#baseurl: ''
# theme: 'codesandnotes'

layoutdir: 'app/templates'
publishdir: 'dist'
#PygmentsCodeFences: "true"

blackfriday:
  angledQuotes: false
  fractions: false
  plainIdAnchors: false

taxonomies:
  tag: 'tags'

params:
  foo: 'bar'

menu:
  main:
    - name: "Preface"
      identifier: "Preface"
      url: "/preface/"
      weight: -20

    - name: "Aspects"
      identifier: "Aspects"
      url: "/aspects/"
      weight: -10

    - name: "Front-end"
      identifier: 'Front-end'
      url: '/front-end/'
      weight: 15

    - name: "CSS"
      identifier: 'CSS'
      url: '/css/'
      weight: 20

    - name: "JavaScript"
      identifier: "JavaScript"
      url: "/javascript/"
      weight: 30

    - name: "Performance"
      identifier: 'Performance'
      url: '/performance/'
      weight: 40

    - name: "Animation"
      weight: 50
      identifier: "Animation"
      url: "/animation/"

    - name: "Content Management"
      identifier: 'Content management'
      url: '/content-management/'
      weight: 52

    - name: "Tools and Workflow"
      identifier: 'Tools and Workflow'
      url: '/tools-and-workflow/'
      weight: 60

    - name: "Roughly learning Ember.js"
      identifier: "Roughly learning Ember-js"
      url: "/roughly-learning-ember-js/"
      weight: 70

    - name: "Ember.js"
      identifier: "Ember-js"
      url: "/ember-js/"
      weight: 71

    - name: "Typography"
      identifier: "Typography"
      url: "/typography/"
      weight: 80

    - name: "Drafts"
      identifier: "_drafts"
      identifier: "_drafts"
      url: "/_drafts/"
      weight: 500
