name = "Codesandnotes"
license = "MIT"
licenselink = "https://github.com/oskarrough/codesandnotes/LICENSE.md"
description = ""
homepage = "https://www.codesandnotes.com"

[author]
  name = "Oskar Rough Mosumgaard"
  homepage = "https://oskarrough.com"
